
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JFrame;

/**
 * Main frame
 * @author KhoiLQCE130023
 */
public class Menu extends javax.swing.JFrame {


    // create new menu
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Image favicon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/favicon.png"));
        this.setIconImage(favicon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttMinimize = new javax.swing.JLabel();
        bttClose = new javax.swing.JLabel();
        bttAbout = new javax.swing.JLabel();
        bttAds2 = new javax.swing.JLabel();
        bttAds1 = new javax.swing.JLabel();
        bttExpert = new javax.swing.JLabel();
        bttNormal = new javax.swing.JLabel();
        bttEasy = new javax.swing.JLabel();
        backgroundMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HNK Minesweeper 2019");
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(bttMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 4, 40, 30));

        bttClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        bttClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttCloseMousePressed(evt);
            }
        });
        getContentPane().add(bttClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1154, 0, -1, -1));

        bttAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttAboutMouseClicked(evt);
            }
        });
        getContentPane().add(bttAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 230, 230));

        bttAds2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAds2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttAds2MouseClicked(evt);
            }
        });
        getContentPane().add(bttAds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, 220, 240));

        bttAds1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAds1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttAds1MouseClicked(evt);
            }
        });
        getContentPane().add(bttAds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 220, 390));

        bttExpert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttExpert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttExpertMouseClicked(evt);
            }
        });
        getContentPane().add(bttExpert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 480, 390));

        bttNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttNormalMouseClicked(evt);
            }
        });
        getContentPane().add(bttNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 460, 240));

        bttEasy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttEasy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttEasyMouseClicked(evt);
            }
        });
        getContentPane().add(bttEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 220, 400));

        backgroundMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        getContentPane().add(backgroundMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttEasyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttEasyMouseClicked
        GamePanel gamePanel = new GamePanel();
        gamePanel.setDif(0);
        gamePanel.setTitle("Easy Level - Minesweeper 2019");
        gamePanel.gameBoard();
        gamePanel.setVisible(true);
        gamePanel.pack();
        gamePanel.setLocationRelativeTo(null);
        gamePanel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bttEasyMouseClicked

    private void bttNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttNormalMouseClicked
        GamePanel gamePanel = new GamePanel();
        gamePanel.setDif(1);
        gamePanel.setTitle("Normal Level - Minesweeper 2019");
        gamePanel.gameBoard();
        gamePanel.setVisible(true);
        gamePanel.pack();
        gamePanel.setLocationRelativeTo(null);
        gamePanel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bttNormalMouseClicked

    private void bttExpertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExpertMouseClicked
        GamePanel gamePanel = new GamePanel();
        gamePanel.setDif(2);
        gamePanel.setTitle("Expert Level - Minesweeper 2019");
        gamePanel.gameBoard();
        gamePanel.setVisible(true);
        gamePanel.pack();
        gamePanel.setLocationRelativeTo(null);
        gamePanel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bttExpertMouseClicked

    private void bttAds1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttAds1MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("http://cantho.fpt.edu.vn").toURI());
        } catch (Exception e) {}
    }//GEN-LAST:event_bttAds1MouseClicked

    private void bttAds2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttAds2MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("https://facebook.com/daihocfptcantho").toURI());
        } catch (Exception e) {}
    }//GEN-LAST:event_bttAds2MouseClicked

    private void bttAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttAboutMouseClicked
        About about = new About();
        about.setVisible(true);
        about.pack();
        about.setLocationRelativeTo(null);
        about.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bttAboutMouseClicked
    
    private int xCoordinate, yCoordinate;
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xCoordinate = evt.getX();
        yCoordinate = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(evt.getXOnScreen() - xCoordinate, evt.getYOnScreen() - yCoordinate);
    }//GEN-LAST:event_formMouseDragged

    private void bttCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCloseMouseEntered
        bttClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_hover.png")));
    }//GEN-LAST:event_bttCloseMouseEntered

    private void bttCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCloseMouseExited
        bttClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png")));
    }//GEN-LAST:event_bttCloseMouseExited

    private void bttCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCloseMousePressed
        
    }//GEN-LAST:event_bttCloseMousePressed

    private void bttMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_bttMinimizeMouseClicked

    private void bttCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bttCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMain;
    private javax.swing.JLabel bttAbout;
    private javax.swing.JLabel bttAds1;
    private javax.swing.JLabel bttAds2;
    private javax.swing.JLabel bttClose;
    private javax.swing.JLabel bttEasy;
    private javax.swing.JLabel bttExpert;
    private javax.swing.JLabel bttMinimize;
    private javax.swing.JLabel bttNormal;
    // End of variables declaration//GEN-END:variables
}
